name: Flutter CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.6'
    - name: Create new flutter project
      run: flutter create --project-name pythoningo temp_app
    - name: List files in workspace
      run: ls -R
    - name: Move app files to new project
      run: |
        rm -rf temp_app/lib
        rm temp_app/pubspec.yaml
        cp -R app/lib temp_app/lib
        cp -R app/assets temp_app/assets
        cp app/pubspec.yaml temp_app/pubspec.yaml
    - run: flutter pub get
      working-directory: ./temp_app
    - run: flutter build apk --release
      working-directory: ./temp_app
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: temp_app/build/app/outputs/flutter-apk/app-release.apk
